name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Run tests
        run: go test -v ./...

      - name: Build for all platforms
        run: |
          mkdir -p release
          GOOS=darwin GOARCH=amd64 go build -o urusai-macos-amd64
          GOOS=darwin GOARCH=arm64 go build -o urusai-macos-arm64
          GOOS=linux GOARCH=amd64 go build -o urusai-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o urusai-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o urusai-windows-amd64.exe
          
          tar -czf release/urusai-macos-amd64.tar.gz urusai-macos-amd64
          tar -czf release/urusai-macos-arm64.tar.gz urusai-macos-arm64
          tar -czf release/urusai-linux-amd64.tar.gz urusai-linux-amd64
          tar -czf release/urusai-linux-arm64.tar.gz urusai-linux-arm64
          zip release/urusai-windows-amd64.zip urusai-windows-amd64.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/urusai-macos-amd64.tar.gz
            release/urusai-macos-arm64.tar.gz
            release/urusai-linux-amd64.tar.gz
            release/urusai-linux-arm64.tar.gz
            release/urusai-windows-amd64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
